cas:
  server:
    address: localhost
server:
  address: localhost
  port: 8082
spring:
  security:
    oauth2:
      client:
        registration:
          oidc:
            client-name: WXTYJK
            client-id: WXTYJK
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: http://${server.address}:8082/login/oauth2/code/oidc
            scope: openid, profile, email, offline_access
            client-authentication-method: client_secret_basic
        provider:
          oidc:
            issuer-uri: http://${cas.server.address}:9080/cas/oidc
            authorization-uri: http://${cas.server.address}:9080/cas/oidc/authorize
            token-uri: http://${cas.server.address}:9080/cas/oidc/token
            user-info-uri: http://${cas.server.address}:9080/cas/oidc/profile
            jwk-set-uri: http://${cas.server.address}:9080/cas/oidc/jwks
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://${server.address}:13306/ainms?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: RootPassword123!
    hikari:
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
logging:
  level:
    ROOT: INFO
    org.hibernate.SQL: INFO
    com.yuzhi.ssodemo: DEBUG